name: docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doc_url: https://bladtcasper-afk.github.io/compas_singular/
          python: "3.12"
          test_docs: false
